### ISSUE TITLE
Login does not work in Firefox Quantum v.68.0.1 (64-bits)

### ISSUE THREAD

**Issue by RafasTavares** [devhubapp/devhub#167] opened 2019-08-13 11:36 UTC
![DevHubDontWork](https://user-images.githubusercontent.com/5371917/62938419-6ac41680-bda5-11e9-9229-7d1d11fc0164.png)

**Comment by brunolemos** [comment] 2019-08-14 20:35
I'm not able to test on Firefox because [Firefox is crashing on macOS Catalina beta 5](https://bugzilla.mozilla.org/show_bug.cgi?id=1570451). Apple will fix on beta 6 but don't know when that will arrive.

But can you try tapping the login button again? I remember facing this some times before and it used to work in the second attempt.

**Comment by brunolemos** [comment] 2019-09-03 04:38
Closing because I could not reproduce (it works fine), and no one else seems to face this. Please try logging in again, maybe it was a one-time thing. Confirm if popups are enabled.

**Closed by brunolemos** 2019-09-03 04:38 UTC
Labels: bug, could not reproduce, web
