### ISSUE TITLE
[Bug] Same HyperLink for repositories with same Owner

### ISSUE THREAD

**Issue by yazdipour** [devhubapp/devhub#27] opened 2018-12-14 14:41 UTC
In dashboard column, repositories with same owner get same `href` in their hyperlink.
In this scenario, all these 5 items, navigate to the first one. `https://github.com/../Name-Generator`
![image](https://user-images.githubusercontent.com/8194807/50008845-9b5f7080-ffca-11e8-892a-c344cacc3278.png)

**Comment by brunolemos** [comment] 2018-12-14 14:44
Hi, I was not able to reproduce the issue. Can you please confirm? Please send a screenshot of the link and browser details. If you can inspect the element to see if their href is correct that would help!

**Comment by yazdipour** [comment] 2018-12-14 14:56
I am using Opera, so I guess it must have a same behavior on Chrome.

![annotation 2018-12-14 182358](https://user-images.githubusercontent.com/8194807/50010018-a10a8580-ffcd-11e8-88bf-3e93c30b1fb9.jpg)

**Comment by brunolemos** [comment] 2018-12-14 17:46
I downloaded Opera to test but was not able to reproduce.
Please send a pull request with the fix!

_I'll close this is no other use reports this bug after a few days._

![devhub-links](https://user-images.githubusercontent.com/619186/50018585-f6876800-ffb6-11e8-9507-d2563a11de9b.gif)

**Comment by yazdipour** [comment] 2018-12-14 18:05
@brunolemos I meant when the owner of the repositories are the same person. 
In this example, those 3 repositories by `XamlBrewer` have problems. Not the others.

![annotation 2018-12-14 182358](https://user-images.githubusercontent.com/8194807/50010018-a10a8580-ffcd-11e8-88bf-3e93c30b1fb9.jpg)

**Closed** 2018-12-15 06:00 UTC
Labels: bug

**Comment by brunolemos** [comment] 2018-12-15 06:01
Fixed! It was a memoization issue. Thanks.

_It'll be deployed soon._
