### ISSUE TITLE
Unable to execute AppImage: The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by gnumoksha** [devhubapp/devhub#199] opened 2019-11-19 14:20 UTC
```console
$ chmod +x DevHub-0.98.5.AppImage
$ ./DevHub-0.98.5.AppImage
[74678:1119/111718.741581:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_DevHubUcWLlF/chrome-sandbox is owned by root and has mode 4755.
[1]    74678 trace trap  ./DevHub-0.98.5.AppImage
```

Relates to https://github.com/electron/electron/issues/17972

**Comment by asyalove** [comment] 2020-02-20 20:07
Duplicate of @
![19336459-CBD0-4CCF-A56E-647DD513C1F6](https://user-images.githubusercontent.com/61271208/74974127-f25da280-5424-11ea-82a1-a857a9deed9e.jpeg)
##
![66E6EC4E-BBC0-40D4-BD25-2791F3CD4F73](https://user-images.githubusercontent.com/61271208/74973851-85e2a380-5424-11ea-85eb-3e03bff8ecfe.jpeg)

**Comment by brunolemos** [comment] 2020-12-08 19:06
Let me know if this still happens on v0.102 or newer

**Closed by brunolemos** 2020-12-08 19:06 UTC
Labels: desktop, good first issue, help wanted, linux
